### ISSUE TITLE
Create git tag for release 1.0.0

### ISSUE THREAD

**Issue by jirutka** [shibukawa/imagesize_py#18]
There’s [imagesize 1.0.0](https://pypi.python.org/pypi/imagesize/1.0.0) on PyPI, but no corresponding tag in this repository. Please add it.

**Comment by sbraz** [comment]
Hi @shibukawa, any chance you could tag adde8c6f54c0f69c8cbd52c14235a5b99b3ed574 as 1.0.0?

**Comment by shibukawa** [comment]
Done!
