### ISSUE TITLE
missing test.jp2 file

### ISSUE THREAD

**Issue by xantares** [shibukawa/imagesize_py#2]
see test/test_get.py:
```
    def test_load_jpeg2000(self):
        width, height = imagesize.get(os.path.join(imagedir, "test.jp2"))
        self.assertEqual(width, 802)
        self.assertEqual(height, 670)
```
also, It could be great if you could setup travis integration to run these tests

**Comment by imz** [comment]
BTW, can you perhaps please help me:

What is the right command to run this `test/test_get.py`?

**Comment by shibukawa** [comment]
I will add travis integration soon.

I use nosetests to run test.

```
$ nosetests test
```

**Comment by shibukawa** [comment]
I added. Thank you.
