### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by kyrias** [shibukawa/imagesize_py#3]
Could you make git tags of releases that you upload to PyPI, both so that it's possible to easily find the exact commit that the release is of, and to have an alternative download location now that PyPI uses hashed URLs instead of making them predictable, which is really annoying when packaging software since now I need to go to PyPI and copy the URL instead of just changing the version number on new releases.

**Comment by shibukawa** [comment]
Thank you for your feedback! I added.
