### ISSUE TITLE
[1.4.0] Missing GIT tag from GH

### ISSUE THREAD

**Issue by hswong3i** [shibukawa/imagesize_py#53]
https://pypi.org/project/imagesize/1.4.0/ is available for pip, but corresponding 1.4.0 GIT tag is now missing for https://github.com/shibukawa/imagesize_py/commit/27427545c9a61b0fea55cf0d323d08c20b231150

**Comment by hswong3i** [comment]
Well case similar as #45...

**Comment by hswong3i** [comment]
And also #39...

@shibukawa my kindly suggestion... Please consider give a quick clean up for https://github.com/shibukawa/imagesize_py/issues...

**Comment by shibukawa** [comment]
Thank you. I for get to add option "--tag".
