### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by julien-duponchelle** [shibukawa/imagesize_py#6]
For our needs I have added a dirty SVG support:
https://github.com/GNS3/gns3-server/blob/4d8cf8460ef35829041432a49c48c8d173b1822a/gns3server/utils/picture.py

Actually it's not battle tested and use in an experimentation with no need for performance,  but I hope it could be usefull for someone

Thanks for the project!

**Comment by noplay** [comment]
Feel free to close this when you want

**Comment by shibukawa** [comment]
I welcome PR to support SVG.

**Comment by cnicodeme** [comment]
The readme indicates the support of SVG.

Should this ticket be closed?
