### ISSUE TITLE
Include the test images in the PyPi release?

### ISSUE THREAD

**Issue by lfam** [shibukawa/imagesize_py#7]
Hi,

Currently, the test files 'test.png' et cetera aren't included in the PyPi tarball.

Will you include the images used by the test suite in the PyPi release tarball?

Or, do you prefer that packagers use the tarballs from GitHub?

**Comment by jakirkham** [comment]
I think this is already handled by PR ( https://github.com/shibukawa/imagesize_py/pull/5 ). Just there hasn't been a release since, so they haven't been included yet. Though the tests should get pulled in whenever the next release is made.
